image: "golang"

before_script:
  - apt update && apt install libgl1-mesa-dev xorg-dev -y
  - go mod download

binary:
  script: ['go build -o xbright *.go']
  artifacts:
    expose_as: 'xbright'
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - './xbright'
    when: on_success
