image: "golang"

stages:
  - build-binary
  - build-deb

before_script:
  - 'apt update && apt install libgl1-mesa-dev xorg-dev -y'
  - 'go mod download'

binary:
  artifacts:
    expose_as: 'binary'
    name: "xbright"
    paths:
      - './xbright'
    when: on_success
  script: 'go build -o xbright *.go'
  stage: build-binary

deb:
  artifacts:
    expose_as: 'deb'
    name: 'xbright.deb'
    paths: ['./xbright.deb']
    when: on_success
  before_script: ['go get fyne.io/fyne/cmd/fyne']
  dependencies:
    - binary
  script: ['bash deb.sh']
  stage: build-deb
